services:
  postgres:
    container_name: qa-forum-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qa-forum
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  
  cache:
    container_name: qa-forum-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data